---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-hostpath
spec:
  containers:
    - image: qualitythought/gameoflife:07112020
      name: gol-container
      volumeMounts:
        - mountPath: /tmp
          name: tmp-volume-host
  volumes:
    - name: tmp-volume-host
      hostPath:
        path: /tmp
        type: Directory
        