---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-azure-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-azure
spec:  
  containers:
    - name: mysql-cont
      image: mysql:8
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'rootroot'
        - name: MYSQL_DATABASE
          value: 'openmrs'
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops
      ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: mysql-azure-pvc
