---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs-label
spec:
  minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        version: "2.60.3"
    spec:
      containers:
        - image: jenkins:2.60.3
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP